---
- name: dotfiles & system bootstrap
  hosts: localhost
  vars:
    is_debian: "{{ ansible_os_family == 'Debian' }}"
    is_macos: "{{ ansible_os_family == 'Darwin' }}"
    is_wsl: "{{ 'microsoft' in ansible_facts['kernel'] }}"
    should_be_root:  "{{ true if is_debian else false }}"
  tasks:
    - name: zsh
      tags: zsh
      import_role:
        name: zsh

    - name: CLI utilities
      tags: utils
      import_role:
        name: utils

    - name: theme setup
      tags: theme
      import_role:
        name: theme

    - name: Gnome GUI tweaks
      tags: gnome
      when: is_debian
      import_role:
        name: gnome

    - name: stow dotfiles
      tags: stow
      import_role:
        name: stow

    - name: neovim
      tags: nvim
      import_role:
        name: nvim

    - name: cleanup
      tags: cleanup
      import_role:
        name: cleanup
