---
- name: dotfiles & system bootstrap
  hosts: localhost
  tasks:
    - name: zsh
      tags: zsh
      import_role:
        name: zsh

    - name: CLI utilities
      tags: utils
      import_role:
        name: utils

    - name: Gnome GUI tweaks
      tags: gnome
      import_role:
        name: gnome

    - name: stow dotfiles
      tags: stow
      import_role:
        name: stow

    - name: neovim
      tags: nvim
      import_role:
        name: nvim
