---
- name: install zsh
  become: "{{ should_be_root }}"
  when: is_debian
  ansible.builtin.package:
    name: zsh
    state: present

- name: ensure zsh plugin directory exists
  ansible.builtin.file:
    path: ~/.zsh/plugins
    state: directory
    mode: '0755'

- name: install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.zsh/plugins/zsh-autosuggestions
    depth: 1

- name: install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.zsh/plugins/zsh-syntax-highlighting
    depth: 1

- name: change user shell to zsh
  become: "{{ should_be_root }}"
  ansible.builtin.user:
    # this ensures that we change the shell _for the user running this playbook_,
    # rather than _for the root user_.
    name: "{{ ansible_facts['user_id'] }}"
    shell: /bin/zsh
