---
- name: install CLI utils with packages
  become: "{{ should_be_root }}"
  ansible.builtin.package:
    name:
      - bat
      - curl
      - eza
      - fzf
      - jq
      - ripgrep
    state: present

- name: install CLI utils with packages (Mac)
  when: is_macos
  become: "{{ should_be_root }}"
  ansible.builtin.package:
    name:
      - fd
    state: present

- name: install CLI utils with packages (Debian)
  when: is_debian
  become: "{{ should_be_root }}"
  ansible.builtin.package:
    name:
      - fd-find
      - python-is-python3
    state: present

- name: install Atuin
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh -s -- --non-interactive
