---
- name: install CLI utils with packages
  become: "{{ should_be_root }}"
  ansible.builtin.package:
    name:
      - bat
      - curl
      - eza
      - fzf
      - gh
      - jq
      - ripgrep
      - zellij
    state: present

- name: install CLI utils with packages (Mac)
  when: is_macos
  become: "{{ should_be_root }}"
  ansible.builtin.package:
    name:
      - fd
      - starship
    state: present

- name: install CLI utils with packages (Debian)
  when: is_debian
  become: "{{ should_be_root }}"
  ansible.builtin.package:
    name:
      - fd-find
      - python-is-python3
    state: present

- name: install Atuin
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh -s -- --non-interactive

- name: ensure local bin directory exists (Debian)
  when: is_debian
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.local/bin"
    state: directory
    mode: '0755'

- name: install Starship (Debian)
  when: is_debian
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -LsSf https://starship.rs/install.sh | sh -s -- --yes --bin-dir "{{ ansible_facts['env']['HOME'] }}/.local/bin"
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.local/bin/starship"
