---
- name: install neovim
  become: true
  ansible.builtin.package:
    name:
      - neovim
    state: present

- name: install neovim packer
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: set up packer deps
  ansible.builtin.shell: |
    nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
